### ISSUE TITLE
Derive first account after a fresh wallet is created with `forc wallet new`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/forc-wallet#130]
Currently `forc wallet new` only creates the wallet itself and does not derive any accounts. Users need to explicitly derive the first account with `forc wallet account new`. We can derive the first account with the wallet to ease the onboarding process a little.

**Comment by sdankel** [comment]
We should do this for `forc wallet import` as well

**Comment by kayagokalp** [comment]
https://github.com/FuelLabs/forc-wallet/blob/2c157b12d766fb708012878dfb06fed8ae7c2c66/src/new.rs#L31-L36

looks like we already derive the first account with forc-new

**Comment by kayagokalp** [comment]
Closing this as already implemented, opened #185 instead.
