### ISSUE TITLE
Prompt user to enter seed phrase whenever we prompt them to create a new wallet

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/forc-wallet#139]
In forc deploy, if there isn't a wallet yet, we allow the user to create a new wallet without exiting the command. If the user has already created a wallet through the browser plugin, and already has a seed phrase, they should be able to enter it rather than creating a new wallet. 

@kayagokalp confirmed that there is a way to import a wallet with forc. We should make it easier for users either by allowing them to enter the seed phrase within the same command, or giving them the CLI command to import the wallet.

**Comment by zees-dev** [comment]
How do we think about the following flow?:
```mermaid
flowchart TD
    A[forc deploy] --> B{Wallet exists?}
    
    B -->|No| C{Show wallet options}
    B -->|Yes| D{Multiple accounts?}
    
    C -->|Create new| E[Generate new wallet]
    C -->|Import existing| F[Enter seed phrase]
    
    E --> G[Store wallet locally]
    F --> G
    
    G --> D
    
    D -->|Yes| H[Select account]
    D -->|No| I[Use default account]
    
    H --> J[Deploy contract]
    I --> J
    
    J --> K{Deployment success?}
    
    K -->|Yes| L[Show success message]
    K -->|No| M[Show error message]
    
    style A fill:#f9f,stroke:#333
    style J fill:#bbf,stroke:#333
    
    classDef decision fill:#ffb,stroke:#333
    class B,C,D,K decision
    ```

**Comment by sdankel** [comment]
This looks like the flow we want! Another feature that would be nice is to support importing by private key or seed phrase. It could be in the same prompt e.g. `Please enter your mnemonic phrase or private key:`

**Comment by zees-dev** [comment]
Import wallet functionality addressed here: https://github.com/FuelLabs/sway/pull/6680
Private key support will require some planning; as stated in: https://github.com/FuelLabs/forc-wallet/issues/215
