### ISSUE TITLE
Use common forc utils for formatting error & warning output

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/forc-wallet#150]
We should use `println_error` instead of `println!`

And we should use `println_warning` for warnings. This will give this plugin a more consistent UX with the rest of forc.

In `main.rs` we should capture the errors and print them with `println_error`

**Comment by levisyin** [comment]
I will draft an pr for this base on #148 that has implement "In main.rs we should capture the errors and print them with println_error"
