### ISSUE TITLE
A more user friendly wallet 

### ISSUE THREAD

**Issue by Speedevs** [FuelLabs/forc-wallet#184]
A more user friendly wallet.
The UI needs to be updated .and easy way to bridge to fuel on the wallet

**Comment by kayagokalp** [comment]
Can you be more specific? What exact feature are you looking for?

**Comment by Speedevs** [comment]
In terms of checking transaction via the wallet it is Buggy and annoying

**Comment by Speedevs** [comment]
Also no good mobile wallet

**Comment by kayagokalp** [comment]
Are you sure that you are talking about the CLI wallet? This repo is for the CLI wallet. The wallet that you use with your terminal `forc wallet ...`. If you want to open an issue about the extension: https://github.com/FuelLabs/fuels-wallet. Also, while opening an issue there, try to be more specific. If you open the issue as "a more user friendly wallet" it will be closed as a spam. If you can explain what are you looking for and not finding at the moment, or what is buggy there is a chance that people help you.

**Comment by kayagokalp** [comment]
Closing this as this is more likely to do with https://github.com/FuelLabs/fuels-wallet
