### ISSUE TITLE
Retrieve `derive_path` from a `const` rather than using a magic literal

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/forc-wallet#28]
See [here](https://github.com/FuelLabs/forc-wallet/pull/24#discussion_r957143902).

**Comment by adlerjohn** [comment]
Should actually get the path from `fuels-rs` rather than duplicating it maybe?

**Comment by kayagokalp** [comment]
Blocked by #44 (which needs a SDK release)
