### ISSUE TITLE
Accept optional phrase as a password field rather than a parameter

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/forc-wallet#35]
Currently, we are accepting the mnemonic phrase as a parameter (to init command) and this would mean, that the phrase will be visible in the user's shell/bash history. We should accept it as a password field so that it is not visible in history.

**Comment by kayagokalp** [comment]
Should we also ask the words one by one for convenience? which would look something like:

```sh
Enter 1st word:
Enter 2nd word:
```

Or should we expect it in one go? I am not sure which one is better in terms of UX. The first option seems a little annoying but entering 12/24 words separated by space without seeing what you already have might be annoying as well.

**Comment by adlerjohn** [comment]
Someone can always type the words in a separate text editor, then paste them. So I would vote for the one-shot input of the entire phrase.
