### ISSUE TITLE
Move `forc-wallet` to `sway` repo

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/forc-wallet#4]
As forc-wallet is another forc plugin, we discussed with @mitchmindtree a couple of days ago the possible pros of moving it to `sway` repo (under `forc-plugins`).

1. `fuelup` can automatically pack `forc-wallet` with other plugins like `forc-fmt` so that it will be installed automatically
2. Documentation for the `forc-wallet` will be automatically added in the appropriate section of the Sway Book
3. We can call `forc-wallet` by executing `forc wallet` as `forc` will assume it is a plugin and try to run it like `forc-wallet` under the hood.

We can discuss here if anyone has some ideas or objections.

**Comment by adlerjohn** [comment]
I'm against putting `forc-wallet` in the `sway` repo since it has nothing to do with Sway. It has to do with interacting with the Fuel chain specifically.

Additionally, the arguments above can apply to `forc-*`, and if taken to their logical extreme means everything should be in the `sway` repo and plugins shouldn't exist.

**Comment by mitchmindtree** [comment]
> I'm against putting forc-wallet in the sway repo since it has nothing to do with Sway. It has to do with interacting with the Fuel chain specifically.

Perhaps we should consider moving out the `forc-explore` command also?

> Additionally, the arguments above can apply to forc-*, and if taken to their logical extreme means everything should be in the sway repo and plugins shouldn't exist.

The intent was only that it might be useful to have all forc plugins *distributed by FuelLabs* under one location alongside forc for documentation consistency and easy fuelup distribution. That said I can empathize with wanting to keep non-Sway-related plugins outside the Sway repo, and we can always update `fuelup`'s plugin index to use the separate repos.
