### ISSUE TITLE
Add a `send` command for transferring assets

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/forc-wallet#65]
This would be useful for quickly topping up test wallets from a CLI, sending some funds to a predicate, etc.

The SDK already [provides helpers for this](https://fuellabs.github.io/fuels-rs/v0.31.1/wallets/transferring-assets.html), so I'd imagine we just provide a CLI wrapper on top.

**Comment by bingcicle** [comment]
I'm imagining something like

`forc account <account_ix> send <address> <amount> <asset_id>`

would work? (To stay consistent with [what fuels-signers is doing](https://docs.rs/fuels-signers/0.38.1/fuels_signers/wallet/struct.WalletUnlocked.html#method.transfer))
