### ISSUE TITLE
Allow wallet to sign bytes

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/forc-wallet#75]
cc @kayagokalp @mitchmindtree 

### Context
- On the Indexer's beta-4 milestone we're trying to implement https://github.com/FuelLabs/fuel-indexer/issues/240
- We would prefer to implement any authentication via what's already available in the Fuel ecosystem -- i.e., use `forc-wallet`
- As it stands (and this could change) we're expecting to implement a method where in which indexer users (those building and deploying indexers) authenticate against indexer operators (those running the actual indexer services) by simply signing some message, then sending that message to an indexer service so that the service can verify that the user signed the message (thus "authenticating" them).
- ⚠️ Note that we would also need some way for the user to export their public key in a way that can easily be sent in an HTTP request
  - The indexer service would use that public key on the backend to assert that the message was signed by the proper usage

### Implementation
- This is just an idea doesn't have to look like this
#### Signatures
```bash
forc-wallet sign --raw 'my super secret message' --account-index 0

> 0xf86c0a8502540be400825208944bbeeb066ed09b7aed07bf39eee0460dfa261520880de0b6b3a7640000801ca0f3ae52c1ef3300f44df0bcfd1341c232ed6134672b16e35699ae3f5fe2493379a023d23d2955a239dd6f61c4e8b2678d174356ff424eac53da53e17706c43ef871
```

- As discussed with @kayagokalp, we could also allow for signing a file (assuming it's not too much additional work)

```bash
forc-wallet sign --file /path/to/file.txt --account-index 0

> 0xf86c0a8502540be400825208944bbeeb066ed09b7aed07bf39eee0460dfa261520880de0b6b3a7640000801ca0f3ae52c1ef3300f44df0bcfd1341c232ed6134672b16e35699ae3f5fe2493379a023d23d2955a239dd6f61c4e8b2678d174356ff424eac53da53e17706c43ef871
```

#### Exporting pubkey
- Assuming current `export` functionality doesn't include the public key with the exported private key
```bash
forc-wallet export --account-index <account_index> --pubkey

> 63FaC9201494f0bd17B9892B9fae4d52fe3BD377
```

**Comment by nfurfaro** [comment]
I think allowing the user to sign a file, i.e: json would be a great addition here.
This would make it easy to sign formatted messages that could be forwarded to contracts, verified and acted on.
There's probably some overlap here with `forc-tx` ?
cc @mitchmindtree

**Comment by mitchmindtree** [comment]
Thanks for opening this @ra0x3! I thought I'd opened an issue for this the other day after our chat @nfurfaro but must have slipped my mind :sweat_smile:

Yes, I think this makes sense on `forc wallet`, and then to have a follow-up PR at `forc-tx` for signing a transaction and reconstructing it with the necessary witness data.
