### ISSUE TITLE
Consider not storing newly derived account addresses in plain text?

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/forc-wallet#77]
Currently, we write newly derived addresses to an `.accounts` file in order to keep track of what addresses have been used so far. This exposes all derived account addresses in plain-text to any user process, which might be unexpected to the user. E.g. the Trezor Suite requires using your hardware wallet to view account addresses, whether previously derived or not.

## Proposed Alternative

Rather than storing full addresses, we may want to consider the following:

1. Only store the *index* of each derived account so that we can keep track of which accounts have already been derived without revealing all derived addresses in plain text.
2. Require the user enters a password for `forc wallet list` or `forc wallet account <ix>` so that they can be derived upon request.

Otherwise, at the very least we should warn the user that derived account addresses are stored in plain text.

This is a bit of a UX trade-off, as some users may not care about exposing their derived public addresses, and prefer to not require inputting a password to retrieve them.

I think it's likely better to assume that the user wants the more secure option, and leave it to the user to manage their own plain-text files of addresses if they wish to do so.

cc @nfurfaro @simonr0204 @adlerjohn thoughts?

**Comment by mitchmindtree** [comment]
Ahh I just noticed the current behaviour was proposed by @adlerjohn in https://github.com/FuelLabs/forc-wallet/pull/19#pullrequestreview-1084609086. Will leave the behaviour as is for now in favour of notifying the user in the help output for the command, but will leave this issue open for discussion.

**Comment by adlerjohn** [comment]
Data point: MEW exports your wallet as an encrypted file with your address in the title.

**Comment by mitchmindtree** [comment]
One attack vector that comes to mind is that any rogue user-level process could fairly trivially replace an address in one of these plain text files at any point in time between when the account is derived, and when the user runs `forc wallet list` or `forc wallet account <ix>`.

Maybe we should output a warning that recommends verifying addresses before using them with anything of value? We probably need to provide a way to actually re-derive an account again securely to do this (or consider not storing addresses *at all*, and always requiring derivation).

**Comment by mitchmindtree** [comment]
I'm thinking we make the default way the safe way, but provide a flag to allow for bypassing re-derivation and reading straight from the cache, i.e.

1. Require a password for `forc wallet list` and `forc wallet account <ix>`.
2. Add a flag (like `--trust-cache` or `--unverified`) that allows for outputting the list without re-derivation (potentially handy for non-interactive scripts etc).

Thoughts?
