### ISSUE TITLE
feat: add the `from` feature

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/forc-wallet#9]
```bash        
# Add a wallet from a private key. Note that this should prompt a password input, so the private key
# won't live in the terminal's history.
forc wallet from

        Private key:
        [enter private key]

        Please enter a password to encrypt this private key:
        [enter once]
        
        Please re-enter:
        [enter again]
 ```

**Comment by adlerjohn** [comment]
This wallet plugin is an HD wallet, no? Therefore, importing a raw private key isn't particularly useful. Importing a mnemonic phrase would be better.

What algorithm will be used for encryption?

**Comment by kayagokalp** [comment]
As of #37, we have `forc-wallet import` which enables our users to import their wallet using their mnemonic phrase. Closing this as it seems we have this now but please re-open if that is not the case.
